# Specifies the buildspec version to ensure AWS CodeBuild interprets the syntax correctly

version: 0.2

env:
  variables:
    REPO_URI: "123456789012.dkr.ecr.us-east-1.amazonaws.com/snowflake-etl-processor"
    IMAGE_TAG: "latest"  # You can change this to a dynamic tag if needed.

phases:
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $REPO_URI
      - echo "Pre-build phase completed."

  build:
    commands:
      - echo "Starting build phase..."
      - echo "Building the Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG
      - echo "Build phase completed."

  post_build:
    commands:
      - echo "Starting post-build phase..."
      - echo "Verifying environment variables:"
      - echo "REPO_URI: $REPO_URI"
      - echo "IMAGE_TAG: $IMAGE_TAG"
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name snowflake-etl-processor --image-uri $REPO_URI:$IMAGE_TAG
      - echo "Post-build phase completed."

artifacts:
  files:
    - buildspec.yml  # Optional: Specify files to retain as artifacts.

